<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="22896" started-at="2021-10-03T22:03:07 COT" finished-at="2021-10-03T22:03:30 COT">
    <groups>
    </groups>
    <test name="Casos de Prueba Carrito de Compras" duration-ms="22896" started-at="2021-10-03T22:03:07 COT" finished-at="2021-10-03T22:03:30 COT">
      <class name="testcases.CasosCarrito">
        <test-method status="PASS" signature="AbrirNavegador(org.testng.ITestContext)[pri:0, instance:testcases.CasosCarrito@2bec854f]" name="AbrirNavegador" is-config="true" duration-ms="6956" started-at="2021-10-03T22:03:00 COT" finished-at="2021-10-03T22:03:07 COT">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@47289387]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AbrirNavegador -->
        <test-method status="PASS" signature="elegirArticulosAzarCarritoCompras()[pri:0, instance:testcases.CasosCarrito@2bec854f]" name="elegirArticulosAzarCarritoCompras" duration-ms="95" started-at="2021-10-03T22:03:07 COT" finished-at="2021-10-03T22:03:08 COT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- elegirArticulosAzarCarritoCompras -->
        <test-method status="PASS" signature="anadirProductosAlCarrito()[pri:0, instance:testcases.CasosCarrito@2bec854f]" name="anadirProductosAlCarrito" duration-ms="22060" started-at="2021-10-03T22:03:08 COT" depends-on-methods="testcases.CasosCarrito.elegirArticulosAzarCarritoCompras" finished-at="2021-10-03T22:03:30 COT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- anadirProductosAlCarrito -->
        <test-method status="FAIL" signature="verificarProductos()[pri:0, instance:testcases.CasosCarrito@2bec854f]" name="verificarProductos" duration-ms="224" started-at="2021-10-03T22:03:30 COT" depends-on-methods="testcases.CasosCarrito.anadirProductosAlCarrito" finished-at="2021-10-03T22:03:30 COT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at testcases.CasosCarrito.verificarProductos(CasosCarrito.java:102)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verificarProductos -->
        <test-method status="PASS" signature="cerrarNavegador()[pri:0, instance:testcases.CasosCarrito@2bec854f]" name="cerrarNavegador" is-config="true" duration-ms="424" started-at="2021-10-03T22:03:31 COT" finished-at="2021-10-03T22:03:31 COT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cerrarNavegador -->
      </class> <!-- testcases.CasosCarrito -->
    </test> <!-- Casos de Prueba Carrito de Compras -->
  </suite> <!-- Suite -->
</testng-results>
