<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6326" started-at="2021-10-02T23:25:38 COT" finished-at="2021-10-02T23:25:44 COT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6326" started-at="2021-10-02T23:25:38 COT" finished-at="2021-10-02T23:25:44 COT">
      <class name="testcases.CasosCarrito">
        <test-method status="PASS" signature="AbrirNavegador()[pri:0, instance:testcases.CasosCarrito@16c069df]" name="AbrirNavegador" is-config="true" duration-ms="3037" started-at="2021-10-02T23:25:35 COT" finished-at="2021-10-02T23:25:38 COT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AbrirNavegador -->
        <test-method status="PASS" signature="elegirArticulosAzarCarritoCompras()[pri:0, instance:testcases.CasosCarrito@16c069df]" name="elegirArticulosAzarCarritoCompras" duration-ms="85" started-at="2021-10-02T23:25:38 COT" finished-at="2021-10-02T23:25:38 COT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- elegirArticulosAzarCarritoCompras -->
        <test-method status="PASS" signature="anadirProductosAlCarrito()[pri:0, instance:testcases.CasosCarrito@16c069df]" name="anadirProductosAlCarrito" duration-ms="5252" started-at="2021-10-02T23:25:38 COT" depends-on-methods="testcases.CasosCarrito.elegirArticulosAzarCarritoCompras" finished-at="2021-10-02T23:25:44 COT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- anadirProductosAlCarrito -->
        <test-method status="FAIL" signature="verificarProductos()[pri:0, instance:testcases.CasosCarrito@16c069df]" name="verificarProductos" duration-ms="930" started-at="2021-10-02T23:25:44 COT" depends-on-methods="testcases.CasosCarrito.anadirProductosAlCarrito" finished-at="2021-10-02T23:25:44 COT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testcases.CasosCarrito.verificarProductos(CasosCarrito.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verificarProductos -->
        <test-method status="PASS" signature="cerrarNavegador()[pri:0, instance:testcases.CasosCarrito@16c069df]" name="cerrarNavegador" is-config="true" duration-ms="267" started-at="2021-10-02T23:25:44 COT" finished-at="2021-10-02T23:25:45 COT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cerrarNavegador -->
      </class> <!-- testcases.CasosCarrito -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
